languageCode = "zh-tw"
title = "KidiVerse"

[params]
  siteName = "KidiVerse"
    description = "Welcome to KidiVerse, your dynamic hub for organizing and exploring a network of insightful notes!"
  author = "Shawn Wu"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
