baseURL = "https://shawnswu.github.io/KidiVerse/"
languageCode = "zh-tw"
title = "KidiVerse"

[params]
  description = "Hi Here is KidiVerse"
  author = "Shawn Wu"

[menu]
  [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 10