baseURL = "http://localhost:1313/"

[server]
  [[server.headers]]
    for = "/*"
    [server.headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, OPTIONS"
      Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"

[params]
  env = "development"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
