# Production base URL – required for GitHub Pages links
baseURL = "https://shawnswu.github.io/KidiVerse/"
languageCode = "zh-tw"
canonifyURLs = true
title = "KidiVerse"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

[params]
  description = "Hi Here is KidiVerse"
  author = "Shawn Wu"