name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Build Knowledge Graph"]
    branches: ["main"]
    types: [completed]
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: List files before build
        run: |
          echo "=== Files before build ==="
          find . -type f | sort
          echo "======================="

      - name: Build with production config
        run: |
          # Clean previous build
          rm -rf public
          
          # Build with production settings
          hugo --minify --environment production --baseURL "https://shawnswu.github.io/KidiVerse/"
          
          # Verify build output
          echo "=== Build output structure ==="
          find public -type f | sort
          
          echo "\n=== CSS Files ==="
          find public -name "*.css" -o -name "*.map" | xargs ls -la
          
          echo "\n=== JS Files ==="
          find public -name "*.js" | xargs ls -la
          
          echo "\n=== Image Files ==="
          find public -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -o -name "*.svg" | xargs ls -la
          
          # Verify CSS file exists and has content
          CSS_FILE=$(find public -name "*.css" | head -1)
          if [ -f "$CSS_FILE" ]; then
            echo "\n=== CSS File Content (first 10 lines) ==="
            head -n 10 "$CSS_FILE"
          else
            echo "\n❌ ERROR: No CSS file found in build output!"
            exit 1
          fi
      - name: Add .nojekyll
        run: touch public/.nojekyll

      - name: List files before deploy
        run: |
          echo "=== Files to be deployed ==="
          find public -type f | sort
          echo "=========================="

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          full_commit_message: "Deploy: Build ${{ github.sha }} [skip ci]"
          commit_message: "Deploy: Build ${{ github.sha }} [skip ci]"
          empty_commit: false
          keep_files: false
          enable_jekyll: false
          allow_empty_commit: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
